[package]
name = "ec2-gui"
version = "0.1.0"
description = "EC2 GUI desktop application"
authors = ["you"]
edition = "2021"

[lib]
name = "ec2_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ssh2 = { version = "0.9", features = ["vendored-openssl"] }
tauri-plugin-store = "2.4.4"
base64 = "0.23.1"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
